name: IPTV Self-Healer
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install requests
      - name: Update Playlist
        run: python update_links.py
      - name: Push Changes
        run: |
          git config --global user.name 'Cyber-Engineer'
          git config --global user.email 'bot@github.com'
          git add playlist.m3u
          git commit -m "Auto-fix links" || exit 0
          git push
